config/routes.rb
Agenda::Application.routes.draw do
  resource :sesion, only: [:new, :create, :destroy], controller: 'sesion'

  resources :eventos

  resources :personas

  root 'sesion#new'

  

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  validates :descripcion, :persona_id, presence: {
    message: 'no puede estar en blanco'
  }

  belongs_to :persona
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_secure_password

  validates :nombre, presence: {
    message: 'no puede estar en blanco'
  }

  has_many :eventos, dependent: :destroy

  def to_s
    [nombre, apellido].compact.join(' ')
  end

  def self.buscar termino
    where 'nombre LIKE :t OR apellido LIKE :t', t: "#{termino}%"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def persona_actual
    @persona_actual ||= Persona.find(session[:persona_id]) if session[:persona_id]
  end
  helper_method :persona_actual

  def requerir_persona
    redirect_to root_url, notice: 'Debe estar autenticado' unless persona_actual
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :requerir_persona
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento creado.' }
        format.json { render action: 'show', status: :created, location: @evento }
      else
        format.html { render action: 'new' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:descripcion, :persona_id)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :requerir_persona
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.buscar(params[:q]).order('apellido')
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona creada' }
        format.json { render action: 'show', status: :created, location: @persona }
      else
        format.html { render action: 'new' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona actualizada' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido, :password, :password_confirmation)
    end
end

app/controllers/sesion_controller.rb
class SesionController < ApplicationController
  def new
  end

  def create
    persona = Persona.find_by(nombre: sesion_params[:nombre])

    if persona && persona.authenticate(sesion_params[:password])
      session[:persona_id] = persona.id
      redirect_to personas_url, notice: 'Has ingresado correctamente'
    else
      flash.now.alert = 'Nombre o clave incorrecto'
      render 'new'
    end
  end

  def destroy
    session[:persona_id] = nil

    redirect_to root_url, notice: 'Has salido correctamente'
  end

  private

    def sesion_params
      params.require(:sesion).permit(:nombre, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
  def ver_todos
    link_to 'Ver todos', personas_path if params[:q].present?
  end
end

app/views/comun/_menu.html.erb
<div class="menu">
  <ul>
    <li><%= link_to 'Personas', personas_path %></li>
    <li><%= link_to 'Eventos', eventos_path %></li>
  </ul>

  <div class="salir">
    <%= link_to 'Salir', sesion_path, method: :delete %>
  </div>
</div>

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guardar la persona, revise los errores</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion, 'Descripción' %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :persona %><br>
    <%= f.text_field(:persona, data: {
      autocomplete_field: true,
      autocomplete_for: '#evento_persona_id',
      autocomplete_url: personas_path(format: :json)
    }) %>
    <%= f.hidden_field :persona_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editar evento</h1>

<%= render 'form' %>

<%= link_to 'Ver', @evento %> |
<%= link_to 'Volver', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listando eventos</h1>

<table>
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Persona</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= link_to evento.descripcion, evento %></td>
        <td><%= link_to evento.persona, evento.persona %></td>
        <td><%= link_to 'Editar', edit_evento_path(evento) %></td>
        <td><%= link_to 'Eliminar', evento, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>Nuevo evento</h1>

<%= render 'form' %>

<%= link_to 'Volver', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripción:</strong>
  <%= @evento.descripcion %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @evento.persona %>
</p>

<%= link_to 'Editar', edit_evento_path(@evento) %> |
<%= link_to 'Volver', eventos_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'comun/menu' if persona_actual %>
  <%= yield %>
</body>
</html>

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2>No se pudo guardar la persona, revise los errores</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :password, 'Contraseña' %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirmación' %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editando persona</h1>

<%= render 'form' %>

<%= link_to 'Ver', @persona %> |
<%= link_to 'Volver', personas_path %>

app/views/personas/index.html.erb
<h1>Listando personas</h1>

<%= form_for :persona, url: personas_path, method: :get do |f| %>
  <%= text_field_tag :q, params[:q] %>

  <%= f.submit 'Buscar' %> <%= ver_todos %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= link_to "#{persona.nombre} #{persona.apellido}", persona %></td>
        <td><%= link_to 'Editar', edit_persona_path(persona) %></td>
        <td><%= link_to 'Eliminar', persona, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>Nueva persona</h1>

<%= render 'form' %>

<%= link_to 'Volver', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>
<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Volver', personas_path %>

app/views/sesion/new.html.erb
<h1>Ingreso</h1>

<%= form_for :sesion, url: sesion_path do |f| %>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :password, 'Clave' %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Ingresar' %>
  </div>
<% end %>

<p><%= flash[:alert] || flash[:notice] %></p>